<?php
/**
 * Copyright © 2011-2017 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 * 
 * See COPYING.txt for license details.
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <dt class="title"><?php /* @noEscape */ echo $title ?></dt>
<?php if ($specificInfo):?>
    <dd class="content">
        <table class="data table">
            <caption class="table-caption"><?php /* @noEscape */ echo $title ?></caption>
            <?php foreach ($specificInfo as $label => $value): ?>
                <tr>
                    <th scope="row"><?php echo $block->escapeHtml($label)?></th>
                    <td>
                        <?php /* @noEscape */ echo nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </dd>
<?php endif;?>
</dl>
<p><?php echo $block->escapeHtml($block->getInfo()->getAdditionalInformation('address')) ?></p>
<p><?php echo $block->escapeHtml($block->getInfo()->getAdditionalInformation('btc_total')) ?></p>
<?php echo $block->getChildHtml() ?>
